### ISSUE TITLE
The city Stanford is not included

### ISSUE THREAD

**Issue by nosarthur** [jazzband/django-cities-light#189]
On the geoname.org website, Standford has the code `PPL`
http://www.geonames.org/5398563/stanford.html

I have the project `settings.py` as
```
CITIES_LIGHT_TRANSLATION_LANGUAGES = ['en']                                            
CITIES_LIGHT_INCLUDE_COUNTRIES = ['US', 'CA', ]                           
CITIES_LIGHT_INCLUDE_CITY_TYPES = ['PPL', 'PPLA', 'PPLA2', ]
```
After running `python3 manage.py cities_light --force-all --progress`, it is still not in the database. Did I do something wrong here?

**Comment by hellerpdx** [comment]
You may need to change the source file. Look in `site-packages/cities_light/settings.py`

`CITY_SOURCES = getattr(settings, 'CITIES_LIGHT_CITY_SOURCES',
    ['http://download.geonames.org/export/dump/cities15000.zip'])`

cities15000.zip has cities with a population over 15000. Stanford has a population of 13809.

cities5000.zip should solve the problem. 

More details here: http://download.geonames.org/export/dump/readme.txt
