### ISSUE TITLE
django-autoslug-iplweb version requirement (1.9.4.dev0)

### ISSUE THREAD

**Issue by dwasyl** [jazzband/django-cities-light#198]
Hi there,

Is there any chance of getting the iplweb requirement updated to the fully released 1.9.4? It was conflicting with some other applications, and there doesn't seem to be much difference.

Thanks

Edit: Looks like this is just #184

**Comment by layoaster** [comment]
By now `django-autoslug-iplweb` version `1.9.5` has been [released](https://pypi.org/project/django-autoslug-iplweb/#history) and still getting the annoying **warning** regarding the version `1.9.4.dev0`

```shell
ERROR: django-cities-light 3.5.0 has requirement django-autoslug-iplweb==1.9.4.dev0, but you'll have django-autoslug-iplweb 1.9.4 which is incompatible.
```

Also looking forward to the requirement's upgrade.

**Comment by jpic** [comment]
It was upgraded in latest releases
