### ISSUE TITLE
Error: cities_light.models.MultipleObjectsReturned

### ISSUE THREAD

**Issue by gabofer82** [jazzband/django-cities-light#216]
Hi:

I get this error as output for ./mange.py cities_light: 
`cities_light.models.MultipleObjectsReturned: get() returned more than one SubRegion -- it returned 18!`

Related Settings for Python 3.7, django 2.2 on Deepin:
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# CITIES LIGHT
# http://www.lingoes.net/en/translator/langcode.htm
CITIES_LIGHT_TRANSLATION_LANGUAGES = ['es', 'pt', 'en']
CITIES_LIGHT_INCLUDE_COUNTRIES = ['UY']
# http://www.geonames.org/export/codes.html
CITIES_LIGHT_INCLUDE_CITY_TYPES = ['PPL']

```
The method expects one object, but get a lot. Why? Any suggestion?

Thankyou!

**Comment by gabofer82** [comment]
The question is why this query:
```
SubRegion.objects.get(
                country_id=country_id, geoname_code=subregion_id).pk
```
get multiple objects? Evidently one objects is expected..

**Comment by bomba1990** [comment]
@gabofer82 IF you use the code from branch development, probably you don't have this issue anymore.

**Comment by bomba1990** [comment]
@gabofer82 the code from the master branch has the issue solved, please test and reopen the issue if necessary.

**Comment by shamanengine** [comment]
It is still not resolved
