### ISSUE TITLE
UNIQUE constraint failed: cities_light_city.region_id, cities_light_city.name'

### ISSUE THREAD

**Issue by gianluigiruggeri** [jazzband/django-cities-light#218]
I'm using current develop version to avoid the error [216](https://github.com/jazzband/django-cities-light/issues/216) about:

but when I run the command cities-light I see some warning/error like this:

WARNING Saving Breitbrunn, Bavaria, Germany failed: IntegrityError('UNIQUE constraint failed: cities_light_city.region_id, cities_light_city.name')

**Comment by iogf** [comment]
I got the same error regarding india.

**Comment by bomba1990** [comment]
@iogf @gianluigiruggeri  the code from the master branch has the issue solved, please test and reopen the issue if necessary.

**Comment by zypro** [comment]
Got this issue now again with version 3.7.0 (with django 3.1.2 and python 3.9)...

**Comment by marianoeramirez** [comment]
@zypro thanks for the comment. please create a new ticket with more information about your error. And try to use the version from the master branch.

**Comment by Agewin** [comment]
Hello, I run the "python manage.py cities_light", the Country, Region and SubRegion worked but i got ,Saving Xintian, Chongqing, China failed: IntegrityError('UNIQUE constraint failed: cities_light_city.region_id, cities_light_city.subregion_id, cities_l
ight_city.name')
Saving Yihe, Chongqing, China failed: IntegrityError('UNIQUE constraint failed: cities_light_city.region_id, cities_light_city.subregion_id, cities_ligh
t_city.name')', for city and its not displaying the list of cities.

**Comment by durmus-pala** [comment]
Hello I got same error during data import for United Kingdom (GB)

**Comment by ValentinKardzhaliev** [comment]
Same error here: 
Saving Buenaventura, Valle del Cauca, Colombia failed: IntegrityError('UNIQUE constraint failed: cities_light_city.region_id, cities_light_city.subregion_id, cities_light_city.slug')
Saving Hayes, England, United Kingdom failed: IntegrityError('UNIQUE constraint failed: cities_light_city.region_id, cities_light_city.subregion_id, cities_light_city.slug')
Saving Panauti, Bagmati Province, Nepal failed: IntegrityError('UNIQUE constraint failed: cities_light_city.region_id, cities_light_city.subregion_id, cities_light_city.slug')
Saving Vincent, California, United States failed: IntegrityError('UNIQUE constraint failed: cities_light_city.region_id, cities_light_city.subregion_id, cities_light_city.slug')

**Comment by teury** [comment]
x2

**Comment by SoftwareCabana** [comment]
same error:
Assuming local download is up to date for http://download.geonames.org/export/dump/countryInfo.txt
Assuming local download is up to date for http://download.geonames.org/export/dump/admin1CodesASCII.txt
Assuming local download is up to date for http://download.geonames.org/export/dump/admin2Codes.txt
Assuming local download is up to date for http://download.geonames.org/export/dump/cities15000.zip
Saving Hayes, England, United Kingdom failed: IntegrityError('UNIQUE constraint failed: cities_light_city.region_id, cities_light_city.subregion_id, cities_light_city.name')
