### ISSUE TITLE
django-autoslug-iplweb dependency does not work with Django 3.1

### ISSUE THREAD

**Issue by SanketDG** [jazzband/django-cities-light#227]
`FieldDoesNotExist` has been moved to `django.core,exceptions`

The original autoslug package has fixed this, but the fork used here has not, hence this is unusable with 3.1

**Comment by marianoeramirez** [comment]
Hi @SanketDG, in the pull request #226 this issue is fixed. We are waiting for someone to review and approve the merge.

**Comment by mpasternak** [comment]
Hi, fork maintainer here. If the original package of auto slug is being maintained perhaps you should switch to it. AFAIR the fork was created because of it and doesn’t contain any extra code or functionality... I could be wrong...

**Comment by marianoeramirez** [comment]
Hi @mpasternak they recently published new versions of the original package, you can see the changes here. https://github.com/justinmayer/django-autoslug/blob/master/CHANGELOG.rst. Looks like recently they had some activity.

**Comment by mpasternak** [comment]
Most of my forks are (sadly) because of unresponsive maintainer. Glad to see django-autoslug coming back!

**Comment by SanketDG** [comment]
@marianoeramirez The PyPI release is yet to be made right?

**Comment by marianoeramirez** [comment]
Yes but we have a different ticket for this #228

**Comment by SanketDG** [comment]
Oops did not look for it, thanks!
