### ISSUE TITLE
Cities_light_city.subregion_id Incorrect

### ISSUE THREAD

**Issue by thisisnotmyuserid** [jazzband/django-cities-light#229]
I think I may have found an issue with how the SubRegion ID is populated in the "Cities_light_city" table. I have used the test project in the main branch and also the tagged 3.7.0 to replicate this issue. I am unfortunately not super confident in my python ability, but I am trying to figure out what is happening but I just have not been able to figure it out yet.

Using the below query:

```sql
select cities_light_country.name as "Country", cities_light_region.name as "Region", cities_light_subregion.name As "SubRegion", cities_light_city.name as "City"
from cities_light_city
join cities_light_country ON cities_light_country.id = cities_light_city.country_id
join cities_light_region ON cities_light_region.id = cities_light_city.region_id
join cities_light_subregion ON cities_light_subregion.id = cities_light_city.subregion_id
Where cities_light_city.name like "%Los Angeles%"
```

I expect to get from that query:
City | SubRegion | Region | City
------------ | -------------|------------ | -------------
Los Angeles | Los Angeles County | California | United States
East Los Angeles | Los Angeles County | California | United States

But instead, what we actually get is:
City | SubRegion | Region | City
------------ | -------------|------------ | -------------
Los Angeles | Dubois County | California | United States
East Los Angeles | Dubois County | California | United States

This is not correct because neither Los Angeles nor East Los Angeles is in Dubois County (Dubois County is in Indiana).

It seems like  def _get_subregion_id is filtering for the country id and sub region id but not the Region ID or somthing.

**Comment by thisisnotmyuserid** [comment]
I think I may have figured it out. I am not super confident though.

```diff
    def _clear_identity_maps(self):
        """Clear identity maps and free some memory."""
        if getattr(self, '_country_codes', False):
            del self._country_codes
        if getattr(self, '_region_codes', False):
            del self._region_codes
        if getattr(self, '_subregion_codes', False):
            del self._subregion_codes
        self._country_codes = {}
        self._region_codes = collections.defaultdict(dict)
+        self._subregion_codes = collections.defaultdict(lambda: collections.defaultdict(dict))
-        self._subregion_codes = collections.defaultdict(dict)

```

and

```diff python
    def _get_subregion_id(self, country_code2, region_id, subregion_id):
        """
        Simple lazy identity map for (country_code2, region_id,
        subregion_id)->subregion
        """
        country_id = self._get_country_id(country_code2)
        if region_id not in self._region_codes[country_id]:
            self._region_codes[country_id][region_id] = Region.objects.get(
                country_id=country_id, geoname_code=region_id).pk

+        if subregion_id not in self._subregion_codes[country_id][region_id]:
+            self._subregion_codes[country_id][region_id][subregion_id] = \
-        if subregion_id not in self._subregion_codes[country_id]:
-            self._subregion_codes[country_id][subregion_id] = \
                SubRegion.objects.get(
                    region_id=self._region_codes[country_id][region_id],
                    geoname_code=subregion_id).pk
+        return self._subregion_codes[country_id][region_id][subregion_id]
-        return self._subregion_codes[country_id][subregion_id]

```

But at the very least the query I used before now shows correctly that Los Angeles is in Los Angeles County.

City | SubRegion | Region | City
------------ | -------------|------------ | -------------
Los Angeles | Los Angeles County | California | United States
East Los Angeles | Los Angeles County | California | United States

**Comment by marianoeramirez** [comment]
@thisisnotmyuserid Thanks for the fix I checked in the code and you are right. 

I did the copy on the code with your improvements and created a pull request with your changes and others with version 3.7.1.
