### ISSUE TITLE
Choose a project Leader for the project

### ISSUE THREAD

**Issue by marianoeramirez** [jazzband/django-cities-light#235]
I create this ticket to select the lead of the project, according to   https://jazzband.co/about/releases and the information on the ticket #210 

The leader of the project will be the person in charge to review and do the releases of the project to PyPI.

I mention here all the persons that participate recently in this project to see if someone else wants to be the leader of the project, or help to select the person. 
@SanketDG @smithdc1 @arsensokolov  @smithdc1 @nguyencg @ngohoangyell @adamb70 @llybin @predatell

**Comment by adamb70** [comment]
@marianoeramirez You have my vote for project leader if you want it. Nobody else has been as active in this package's development recently.

**Comment by SanketDG** [comment]
My vote also goes to @marianoeramirez for all of the compatibility work + other fixes recently.

**Comment by smithdc1** [comment]
@marianoeramirez seems to be doing much of the work here. Thanks for reviewing and merging my recent pull requests.

**Comment by marianoeramirez** [comment]
Ok, thanks!! Let's wait until next Friday to see if someone else appears, to request the modification to Jazzband.  And hopefully, deploy to Pypi next weekend.

**Comment by marianoeramirez** [comment]
Like no one else appears. I will close this ticket and mention to @jezdez #210
